version: '3.2'

services: 
  test-api-synvia:
    image: evandroneris/api-synvia
    container_name: api-synvia
    restart: unless-stopped

    build: 
      context: ./
      dockerfile: Dockerfile

    volumes: 
     - ./:/node/app
     - /node/app/node_modules/bcrypt/
     - /node/app/node_modules/sqlite3/

    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - NODE_ENV=development
